export const CLEAR_ALL = 'CLEAR_ALL'
export const ADD = 'ADD'
export const SUBTRACT = 'SUBTRACT'
export const MULTIPLY = 'MULTIPLY'
export const DIVIDE = 'DIVIDE'
export const INPUT_NUMBER = 'INPUT_NUMBER'
export const INPUT_DECIMAL = 'INPUT_DECIMAL'
export const EQUAL = 'EQUAL'